name: build

on: push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v6.0.1
          target: esp32
